site_name: EHFAKE - Documentação
site_description: Documentação técnica do projeto EHFAKE
site_author: Lab Livre - UnB
repo_url: https://github.com/EH-FAKE/docs
repo_name: EHFAKE - Docs

site_url: https://eh-fake.github.io/docs/  
edit_uri: edit/main/docs/

theme:
  name: material
  language: pt-BR
  features:
    - navigation.tabs
    - navigation.expand
    - toc.integrate
    - search.highlight
    - search.suggest

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - minify:
      minify_html: true

nav:
  - Início: index.md
  - Atas de Reunião:
    - Ata 1: atas/ata-1.md
    - Ata 2: atas/ata-2.md
  - Guia de Contribuição:
    - Política de Branches: guia-de-contribuicao/politica-de-branches.md
    - Política de Commits: guia-de-contribuicao/politica-de-commits.md
  - Release I:
    - Apresentação: release1/apresentacao.md
    - Checklist de Entrega: release1/checklist.md
    - Arquitetura de Solução: release1/arquitetura-solucao.md
    - Backlog: release1/backlog.md
    - Sistema de governança: release1/sistema-governanca.md


